// This Pine Script™ code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/

//@version=5
strategy("Simple MA Cross STRAT", overlay=true)

ema20 = ta.ema(close, 20)
ema50 = ta.ema(close, 50)

long = ema20 > ema50
short = ema20 < ema50

longCondition = long and long[10] and not long[11]
shortCondition = short and short[10] and not short[11]

closeLong = ema20 < ema50 and not long[11]
closeShort = ema20 > ema50 and not short[11]

plot(ema20, title = "20", color = color.blue, linewidth = 3)
plot(ema50, title = "50", color = color.purple, linewidth = 2)

start = timestamp(2024, 1, 1, 0, 0)
end = timestamp(2024, 4, 1, 0, 0)

if time >= start and time <= end
    if longCondition
        strategy.entry("Long", strategy.long, 0.002, comment = "LONG")

    if shortCondition
        strategy.entry("Short", strategy.short, 0.002, comment = "SHORT")

    if closeLong
        strategy.close("Long", comment = "SELL")

    if closeShort
        strategy.close("Shåort", comment = "COVER")

// longCondition = ta.crossover(ta.sma(close, 14), ta.sma(close, 28))
// if (longCondition)
//     strategy.entry("My Long Entry Id", strategy.long)

// shortCondition = ta.crossunder(ta.sma(close, 14), ta.sma(close, 28))
// if (shortCondition)
//     strategy.entry("My Short Entry Id", strategy.short)
